#!/usr/bin/env python3
"""Generate esphome/tree_coords.h from the CircuitPython coordinate data.

Single source of truth: tree/coordinates.csv (x,y,z per LED) and tree/segments.csv
(one segment id 0-4 per LED, 0=trunk, 1-4=branches). The ESPHome effect lambdas
read the emitted C++ array, so re-run this whenever the coordinates or segmentation
change:

    venv/bin/python tools/gen_esphome_coords.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COORDS = os.path.join(ROOT, "tree", "coordinates.csv")
SEGS = os.path.join(ROOT, "tree", "segments.csv")
OUT = os.path.join(ROOT, "esphome", "tree_coords.h")

NUM_LEDS = 100  # physical strand length


def read_coords():
    rows = []
    with open(COORDS) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            x, y, z = (int(v) for v in line.split(","))
            rows.append((x, y, z))
    return rows


def read_segs():
    segs = []
    with open(SEGS) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            segs.append(int(line))
    return segs


def main():
    coords = read_coords()
    segs = read_segs()

    if not coords:
        raise SystemExit("no coordinates read")

    # Pad/truncate both to the physical strand length so the C++ array, the strip
    # length, and the effect loops all agree. Short coordinate files repeat the
    # last position (the CircuitPython app leaves such LEDs unlit; lighting them at
    # a nearby position is the friendlier default for a full-strand render).
    if len(coords) < NUM_LEDS:
        coords += [coords[-1]] * (NUM_LEDS - len(coords))
    coords = coords[:NUM_LEDS]
    segs = (segs + [0] * NUM_LEDS)[:NUM_LEDS]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Generated by tools/gen_esphome_coords.py — do not edit by hand.\n")
        f.write("// Source: tree/coordinates.csv + tree/segments.csv\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write(f"#define TREE_NUM_LEDS {NUM_LEDS}\n\n")
        f.write("struct TreeLED { float x, y, z; uint8_t seg; };\n\n")
        f.write(f"static const TreeLED TREE_LEDS[TREE_NUM_LEDS] = {{\n")
        for (x, y, z), s in zip(coords, segs):
            f.write(f"  {{{x}.0f, {y}.0f, {z}.0f, {s}}},\n")
        f.write("};\n")

    print(f"wrote {OUT} ({NUM_LEDS} LEDs)")


if __name__ == "__main__":
    main()
